version: "3"
services:
  web:
    build: 
        context: .
        dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/david/davidbertozzi-server
      - /home/david/davidbertozzi-server/node_modules
      - /home/david/davidbertozzi-server/src
